In [1]:
import cv2
import matplotlib.pyplot as plt

In [2]:
image_gray = cv2.imread('/zhome/ac/d/174101/thesis/test.jpeg')
print(image_gray)

[[[ 82  82  82]
  [ 67  67  67]
  [ 45  45  45]
  ...
  [ 68  68  68]
  [ 11  11  11]
  [  2   2   2]]

 [[ 45  45  45]
  [ 16  16  16]
  [ 64  64  64]
  ...
  [ 62  62  62]
  [ 72  72  72]
  [ 26  26  26]]

 [[ 58  58  58]
  [ 39  39  39]
  [ 28  28  28]
  ...
  [ 83  83  83]
  [ 55  55  55]
  [ 65  65  65]]

 ...

 [[137 137 137]
  [ 82  82  82]
  [125 125 125]
  ...
  [171 171 171]
  [153 153 153]
  [153 153 153]]

 [[139 139 139]
  [117 117 117]
  [133 133 133]
  ...
  [101 101 101]
  [ 87  87  87]
  [ 63  63  63]]

 [[135 135 135]
  [145 145 145]
  [132 132 132]
  ...
  [100 100 100]
  [120 120 120]
  [ 82  82  82]]]


In [3]:
from torchvision.transforms import v2
import torch

In [10]:
class ComputeMeanStdNormalize:
    def __init__(self):
        self.mean = 0.
        self.std = 0.
        self.num_samples = 0

    def __call__(self, img):
        # Incrementally update mean and std
        img = torch.tensor(img, dtype=torch.float32) / 255.  # Convert image to tensor and normalize
        self.mean += torch.mean(img, dim=(0, 1))
        self.std += torch.std(img, dim=(0, 1))
        self.num_samples += 1
        return img

    def get_mean_std(self):
        # Calculate mean and std across all batches
        return self.mean / self.num_samples, self.std / self.num_samples

In [12]:
transform = v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)])
img_tr = transform(image_gray)
print(img_tr) 

Image([[[0.3216, 0.2627, 0.1765,  ..., 0.2667, 0.0431, 0.0078],
        [0.1765, 0.0627, 0.2510,  ..., 0.2431, 0.2824, 0.1020],
        [0.2275, 0.1529, 0.1098,  ..., 0.3255, 0.2157, 0.2549],
        ...,
        [0.5373, 0.3216, 0.4902,  ..., 0.6706, 0.6000, 0.6000],
        [0.5451, 0.4588, 0.5216,  ..., 0.3961, 0.3412, 0.2471],
        [0.5294, 0.5686, 0.5176,  ..., 0.3922, 0.4706, 0.3216]],

       [[0.3216, 0.2627, 0.1765,  ..., 0.2667, 0.0431, 0.0078],
        [0.1765, 0.0627, 0.2510,  ..., 0.2431, 0.2824, 0.1020],
        [0.2275, 0.1529, 0.1098,  ..., 0.3255, 0.2157, 0.2549],
        ...,
        [0.5373, 0.3216, 0.4902,  ..., 0.6706, 0.6000, 0.6000],
        [0.5451, 0.4588, 0.5216,  ..., 0.3961, 0.3412, 0.2471],
        [0.5294, 0.5686, 0.5176,  ..., 0.3922, 0.4706, 0.3216]],

       [[0.3216, 0.2627, 0.1765,  ..., 0.2667, 0.0431, 0.0078],
        [0.1765, 0.0627, 0.2510,  ..., 0.2431, 0.2824, 0.1020],
        [0.2275, 0.1529, 0.1098,  ..., 0.3255, 0.2157, 0.2549],
        ..

In [9]:
import matplotlib.pyplot as plt
import numpy as np

plt.imshow(np.array(img_tr.transpose(1, 2, 0)))
plt.show

TypeError: transpose() received an invalid combination of arguments - got (int, int, int), but expected one of:
 * (int dim0, int dim1)
 * (name dim0, name dim1)


In [9]:
mean, std = img_tr.mean([1,2]), img_tr.std([1,2])
print("mean and std before normalize:")
print("Mean of the image:", mean)
print("Std of the image:", std)

mean and std before normalize:
Mean of the image: tensor([0.6762, 0.6762, 0.6762])
Std of the image: tensor([0.2395, 0.2395, 0.2395])
